apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pvlo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-pvlo@sha256:d0cb634e902babe4cd1c7dbd5036359ccc64f08f376634a1f225a7116e8e306f
        name: my-nodejs
        resources: {}
status: {}
